import type { Layout } from "./types";

/** English US (ANSI). */
export const enUS: Layout = {
  id: "en-us",
  locale: "en",
  iso: false,
  keys: {
    Backquote: { base: "`", shift: "~" },
    Digit1: { base: "1", shift: "!" },
    Digit2: { base: "2", shift: "@" },
    Digit3: { base: "3", shift: "#" },
    Digit4: { base: "4", shift: "$" },
    Digit5: { base: "5", shift: "%" },
    Digit6: { base: "6", shift: "^" },
    Digit7: { base: "7", shift: "&" },
    Digit8: { base: "8", shift: "*" },
    Digit9: { base: "9", shift: "(" },
    Digit0: { base: "0", shift: ")" },
    Minus: { base: "-", shift: "_" },
    Equal: { base: "=", shift: "+" },
    KeyQ: { base: "q", shift: "Q" },
    KeyW: { base: "w", shift: "W" },
    KeyE: { base: "e", shift: "E" },
    KeyR: { base: "r", shift: "R" },
    KeyT: { base: "t", shift: "T" },
    KeyY: { base: "y", shift: "Y" },
    KeyU: { base: "u", shift: "U" },
    KeyI: { base: "i", shift: "I" },
    KeyO: { base: "o", shift: "O" },
    KeyP: { base: "p", shift: "P" },
    BracketLeft: { base: "[", shift: "{" },
    BracketRight: { base: "]", shift: "}" },
    Backslash: { base: "\\", shift: "|" },
    KeyA: { base: "a", shift: "A" },
    KeyS: { base: "s", shift: "S" },
    KeyD: { base: "d", shift: "D" },
    KeyF: { base: "f", shift: "F" },
    KeyG: { base: "g", shift: "G" },
    KeyH: { base: "h", shift: "H" },
    KeyJ: { base: "j", shift: "J" },
    KeyK: { base: "k", shift: "K" },
    KeyL: { base: "l", shift: "L" },
    Semicolon: { base: ";", shift: ":" },
    Quote: { base: "'", shift: '"' },
    KeyZ: { base: "z", shift: "Z" },
    KeyX: { base: "x", shift: "X" },
    KeyC: { base: "c", shift: "C" },
    KeyV: { base: "v", shift: "V" },
    KeyB: { base: "b", shift: "B" },
    KeyN: { base: "n", shift: "N" },
    KeyM: { base: "m", shift: "M" },
    Comma: { base: ",", shift: "<" },
    Period: { base: ".", shift: ">" },
    Slash: { base: "/", shift: "?" },
    Space: { base: " " },
  },
};
