import type { Layout } from "./types";

/** Türkçe F (ISO) — TS 3284 standardı. */
export const trF: Layout = {
  id: "tr-f",
  locale: "tr",
  iso: true,
  keys: {
    Backquote: { base: "+", shift: "*", altGr: "¬" },
    Digit1: { base: "1", shift: "!", altGr: "¹" },
    Digit2: { base: "2", shift: '"', altGr: "²" },
    Digit3: { base: "3", shift: "^", altGr: "#" },
    Digit4: { base: "4", shift: "$", altGr: "¼" },
    Digit5: { base: "5", shift: "%", altGr: "½" },
    Digit6: { base: "6", shift: "&", altGr: "¾" },
    Digit7: { base: "7", shift: "'", altGr: "{" },
    Digit8: { base: "8", shift: "(", altGr: "[" },
    Digit9: { base: "9", shift: ")", altGr: "]" },
    Digit0: { base: "0", shift: "=", altGr: "}" },
    Minus: { base: "/", shift: "?", altGr: "\\" },
    Equal: { base: "-", shift: "_", altGr: "|" },
    KeyQ: { base: "f", shift: "F", altGr: "@" },
    KeyW: { base: "g", shift: "G" },
    KeyE: { base: "ğ", shift: "Ğ" },
    KeyR: { base: "ı", shift: "I" },
    KeyT: { base: "o", shift: "O" },
    KeyY: { base: "d", shift: "D" },
    KeyU: { base: "r", shift: "R" },
    KeyI: { base: "n", shift: "N" },
    KeyO: { base: "h", shift: "H" },
    KeyP: { base: "p", shift: "P" },
    BracketLeft: { base: "q", shift: "Q" },
    BracketRight: { base: "w", shift: "W", altGr: "~" },
    KeyA: { base: "u", shift: "U" },
    KeyS: { base: "i", shift: "İ" },
    KeyD: { base: "e", shift: "E", altGr: "€" },
    KeyF: { base: "a", shift: "A" },
    KeyG: { base: "ü", shift: "Ü" },
    KeyH: { base: "t", shift: "T" },
    KeyJ: { base: "k", shift: "K" },
    KeyK: { base: "m", shift: "M" },
    KeyL: { base: "l", shift: "L" },
    Semicolon: { base: "y", shift: "Y" },
    Quote: { base: "ş", shift: "Ş" },
    Backslash: { base: "x", shift: "X", altGr: "`" },
    IntlBackslash: { base: "<", shift: ">", altGr: "|" },
    KeyZ: { base: "j", shift: "J" },
    KeyX: { base: "ö", shift: "Ö" },
    KeyC: { base: "v", shift: "V" },
    KeyV: { base: "c", shift: "C" },
    KeyB: { base: "ç", shift: "Ç" },
    KeyN: { base: "z", shift: "Z" },
    KeyM: { base: "s", shift: "S" },
    Comma: { base: "b", shift: "B" },
    Period: { base: ".", shift: ":" },
    Slash: { base: ",", shift: ";" },
    Space: { base: " " },
  },
};
